wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
100%|██████████| 25/25 [07:02<00:00, 16.90s/it]
{'loss': 0.0, 'grad_norm': 0.2790698707103729, 'learning_rate': 1.9200000000000003e-05, 'completion_length': 85.703125, 'rewards/reward_function': -277.390625, 'reward': -277.390625, 'reward_std': 80.39103317260742, 'kl': 0.0, 'epoch': 0.04}
{'loss': 0.0001, 'grad_norm': 0.2724272310733795, 'learning_rate': 1.8400000000000003e-05, 'completion_length': 87.6875, 'rewards/reward_function': -286.140625, 'reward': -286.140625, 'reward_std': 63.79728126525879, 'kl': 0.0016600813250988722, 'epoch': 0.08}
{'loss': 0.0001, 'grad_norm': 0.25853413343429565, 'learning_rate': 1.76e-05, 'completion_length': 87.5625, 'rewards/reward_function': -298.046875, 'reward': -298.046875, 'reward_std': 73.8387680053711, 'kl': 0.0017058048397302628, 'epoch': 0.12}
{'loss': 0.0001, 'grad_norm': 0.30304569005966187, 'learning_rate': 1.6800000000000002e-05, 'completion_length': 82.296875, 'rewards/reward_function': -267.328125, 'reward': -267.328125, 'reward_std': 82.23364067077637, 'kl': 0.0015851706266403198, 'epoch': 0.16}
{'loss': 0.0001, 'grad_norm': 0.3625846803188324, 'learning_rate': 1.6000000000000003e-05, 'completion_length': 88.328125, 'rewards/reward_function': -293.609375, 'reward': -293.609375, 'reward_std': 62.49842071533203, 'kl': 0.0019628938753157854, 'epoch': 0.2}
{'loss': 0.0001, 'grad_norm': 0.22889812290668488, 'learning_rate': 1.5200000000000002e-05, 'completion_length': 90.65625, 'rewards/reward_function': -298.109375, 'reward': -298.109375, 'reward_std': 60.83298110961914, 'kl': 0.0016529691638424993, 'epoch': 0.24}
{'loss': 0.0001, 'grad_norm': 0.2528606057167053, 'learning_rate': 1.4400000000000001e-05, 'completion_length': 89.5, 'rewards/reward_function': -291.0625, 'reward': -291.0625, 'reward_std': 54.633296966552734, 'kl': 0.001716800092253834, 'epoch': 0.28}
{'loss': 0.0001, 'grad_norm': 0.25518667697906494, 'learning_rate': 1.3600000000000002e-05, 'completion_length': 88.8125, 'rewards/reward_function': -281.671875, 'reward': -281.671875, 'reward_std': 66.85892295837402, 'kl': 0.001493229006882757, 'epoch': 0.32}
{'loss': 0.0001, 'grad_norm': 0.2594229578971863, 'learning_rate': 1.2800000000000001e-05, 'completion_length': 81.796875, 'rewards/reward_function': -264.671875, 'reward': -264.671875, 'reward_std': 81.63549041748047, 'kl': 0.0016643339185975492, 'epoch': 0.36}
{'loss': 0.0001, 'grad_norm': 0.3658095598220825, 'learning_rate': 1.2e-05, 'completion_length': 79.921875, 'rewards/reward_function': -259.46875, 'reward': -259.46875, 'reward_std': 95.23106002807617, 'kl': 0.0017163836164399981, 'epoch': 0.4}
{'loss': 0.0001, 'grad_norm': 0.21451084315776825, 'learning_rate': 1.1200000000000001e-05, 'completion_length': 87.59375, 'rewards/reward_function': -277.265625, 'reward': -277.265625, 'reward_std': 58.09666442871094, 'kl': 0.0015620781923644245, 'epoch': 0.44}
{'loss': 0.0001, 'grad_norm': 0.20572827756404877, 'learning_rate': 1.04e-05, 'completion_length': 82.578125, 'rewards/reward_function': -282.828125, 'reward': -282.828125, 'reward_std': 77.48200607299805, 'kl': 0.0015648936969228089, 'epoch': 0.48}
{'loss': 0.0001, 'grad_norm': 0.3084409534931183, 'learning_rate': 9.600000000000001e-06, 'completion_length': 80.6875, 'rewards/reward_function': -277.0625, 'reward': -277.0625, 'reward_std': 91.28536224365234, 'kl': 0.0015668447595089674, 'epoch': 0.52}
{'loss': 0.0001, 'grad_norm': 0.2437465339899063, 'learning_rate': 8.8e-06, 'completion_length': 85.0, 'rewards/reward_function': -293.953125, 'reward': -293.953125, 'reward_std': 64.88169479370117, 'kl': 0.0015933850081637502, 'epoch': 0.56}
{'loss': 0.0001, 'grad_norm': 0.26772886514663696, 'learning_rate': 8.000000000000001e-06, 'completion_length': 87.328125, 'rewards/reward_function': -288.96875, 'reward': -288.96875, 'reward_std': 60.14434814453125, 'kl': 0.0018153013661503792, 'epoch': 0.6}
{'loss': 0.0001, 'grad_norm': 0.2647325098514557, 'learning_rate': 7.2000000000000005e-06, 'completion_length': 82.234375, 'rewards/reward_function': -281.390625, 'reward': -281.390625, 'reward_std': 94.85498046875, 'kl': 0.00168025481980294, 'epoch': 0.64}
{'loss': 0.0001, 'grad_norm': 0.27615970373153687, 'learning_rate': 6.4000000000000006e-06, 'completion_length': 86.78125, 'rewards/reward_function': -285.109375, 'reward': -285.109375, 'reward_std': 75.94940948486328, 'kl': 0.0015007143374532461, 'epoch': 0.68}
{'loss': 0.0001, 'grad_norm': 0.25556236505508423, 'learning_rate': 5.600000000000001e-06, 'completion_length': 87.5625, 'rewards/reward_function': -281.484375, 'reward': -281.484375, 'reward_std': 66.69258499145508, 'kl': 0.0016888820682652295, 'epoch': 0.72}
{'loss': 0.0001, 'grad_norm': 0.2600763440132141, 'learning_rate': 4.800000000000001e-06, 'completion_length': 85.40625, 'rewards/reward_function': -269.09375, 'reward': -269.09375, 'reward_std': 71.68644714355469, 'kl': 0.001758801401592791, 'epoch': 0.76}
{'loss': 0.0001, 'grad_norm': 0.3275821805000305, 'learning_rate': 4.000000000000001e-06, 'completion_length': 80.921875, 'rewards/reward_function': -268.359375, 'reward': -268.359375, 'reward_std': 77.93945693969727, 'kl': 0.0020186328911222517, 'epoch': 0.8}
{'loss': 0.0001, 'grad_norm': 0.26480093598365784, 'learning_rate': 3.2000000000000003e-06, 'completion_length': 89.703125, 'rewards/reward_function': -284.3125, 'reward': -284.3125, 'reward_std': 58.80084228515625, 'kl': 0.0020952667109668255, 'epoch': 0.84}
{'loss': 0.0001, 'grad_norm': 0.2721506953239441, 'learning_rate': 2.4000000000000003e-06, 'completion_length': 88.671875, 'rewards/reward_function': -283.21875, 'reward': -283.21875, 'reward_std': 67.56355285644531, 'kl': 0.0016636900254525244, 'epoch': 0.88}
{'loss': 0.0001, 'grad_norm': 0.33128631114959717, 'learning_rate': 1.6000000000000001e-06, 'completion_length': 85.609375, 'rewards/reward_function': -270.484375, 'reward': -270.484375, 'reward_std': 79.0280876159668, 'kl': 0.0016833643894642591, 'epoch': 0.92}
{'loss': 0.0001, 'grad_norm': 0.26409977674484253, 'learning_rate': 8.000000000000001e-07, 'completion_length': 86.1875, 'rewards/reward_function': -287.359375, 'reward': -287.359375, 'reward_std': 77.40628051757812, 'kl': 0.0017828972195275128, 'epoch': 0.96}
{'loss': 0.0001, 'grad_norm': 0.22775086760520935, 'learning_rate': 0.0, 'completion_length': 85.765625, 'rewards/reward_function': -277.0625, 'reward': -277.0625, 'reward_std': 66.46919631958008, 'kl': 0.0017105351435020566, 'epoch': 1.0}
{'train_runtime': 422.5779, 'train_samples_per_second': 0.473, 'train_steps_per_second': 0.059, 'train_loss': 6.534868851304054e-05, 'epoch': 1.0}
model.safetensors: 100%|██████████| 269M/269M [00:17<00:00, 15.8MB/s] 
Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1486, in _raise_on_head_call_error
    raise head_call_error
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 280, in _request_wrapper
    response = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 304, in _request_wrapper
    hf_raise_for_status(response)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 458, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-67dc21dc-66868d554ed168db547b1d1d;70deb3df-d555-4907-b06b-8ca689c53d76)

Repository Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/dssc/scandu00/rebus-grpo/tutorial.py", line 97, in <module>
    generator = pipeline("text-generation", model="SmolGRPO-135M")
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/pipelines/__init__.py", line 812, in pipeline
    resolved_config_file = cached_file(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: SmolGRPO-135M is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1486, in _raise_on_head_call_error
    raise head_call_error
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 280, in _request_wrapper
    response = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 304, in _request_wrapper
    hf_raise_for_status(response)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 458, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-67dc21dc-66868d554ed168db547b1d1d;70deb3df-d555-4907-b06b-8ca689c53d76)

Repository Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/dssc/scandu00/rebus-grpo/tutorial.py", line 97, in <module>
    generator = pipeline("text-generation", model="SmolGRPO-135M")
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/pipelines/__init__.py", line 812, in pipeline
    resolved_config_file = cached_file(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: SmolGRPO-135M is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
