wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
100%|██████████| 25/25 [07:07<00:00, 17.12s/it]
{'loss': 0.0, 'grad_norm': 0.28603971004486084, 'learning_rate': 1.9200000000000003e-05, 'completion_length': 85.703125, 'rewards/reward_function': -277.390625, 'reward': -277.390625, 'reward_std': 80.39103317260742, 'kl': 0.0, 'epoch': 0.04}
{'loss': 0.0001, 'grad_norm': 0.298767626285553, 'learning_rate': 1.8400000000000003e-05, 'completion_length': 89.796875, 'rewards/reward_function': -293.828125, 'reward': -293.828125, 'reward_std': 72.8023910522461, 'kl': 0.0015340765239670873, 'epoch': 0.08}
{'loss': 0.0001, 'grad_norm': 0.23397500813007355, 'learning_rate': 1.76e-05, 'completion_length': 89.46875, 'rewards/reward_function': -303.203125, 'reward': -303.203125, 'reward_std': 61.34514617919922, 'kl': 0.001690641453024, 'epoch': 0.12}
{'loss': 0.0001, 'grad_norm': 0.316050261259079, 'learning_rate': 1.6800000000000002e-05, 'completion_length': 84.625, 'rewards/reward_function': -281.109375, 'reward': -281.109375, 'reward_std': 93.17843627929688, 'kl': 0.0015482019516639411, 'epoch': 0.16}
{'loss': 0.0001, 'grad_norm': 0.2877937853336334, 'learning_rate': 1.6000000000000003e-05, 'completion_length': 87.609375, 'rewards/reward_function': -288.96875, 'reward': -288.96875, 'reward_std': 75.16933059692383, 'kl': 0.0018622069037519395, 'epoch': 0.2}
{'loss': 0.0001, 'grad_norm': 0.268630713224411, 'learning_rate': 1.5200000000000002e-05, 'completion_length': 89.546875, 'rewards/reward_function': -290.5, 'reward': -290.5, 'reward_std': 61.58219909667969, 'kl': 0.0018003632430918515, 'epoch': 0.24}
{'loss': 0.0001, 'grad_norm': 0.2901913523674011, 'learning_rate': 1.4400000000000001e-05, 'completion_length': 83.375, 'rewards/reward_function': -275.140625, 'reward': -275.140625, 'reward_std': 74.13127899169922, 'kl': 0.0015414284425787628, 'epoch': 0.28}
{'loss': 0.0001, 'grad_norm': 0.2668258547782898, 'learning_rate': 1.3600000000000002e-05, 'completion_length': 88.390625, 'rewards/reward_function': -286.125, 'reward': -286.125, 'reward_std': 71.82349014282227, 'kl': 0.0015289645525626838, 'epoch': 0.32}
{'loss': 0.0001, 'grad_norm': 0.2861950099468231, 'learning_rate': 1.2800000000000001e-05, 'completion_length': 84.1875, 'rewards/reward_function': -276.609375, 'reward': -276.609375, 'reward_std': 85.87775039672852, 'kl': 0.001564545149449259, 'epoch': 0.36}
{'loss': 0.0001, 'grad_norm': 0.39603951573371887, 'learning_rate': 1.2e-05, 'completion_length': 80.796875, 'rewards/reward_function': -253.765625, 'reward': -253.765625, 'reward_std': 89.81803894042969, 'kl': 0.0017751521081663668, 'epoch': 0.4}
{'loss': 0.0001, 'grad_norm': 0.243144229054451, 'learning_rate': 1.1200000000000001e-05, 'completion_length': 87.0, 'rewards/reward_function': -281.78125, 'reward': -281.78125, 'reward_std': 63.14755630493164, 'kl': 0.0016199165838770568, 'epoch': 0.44}
{'loss': 0.0001, 'grad_norm': 0.26129814982414246, 'learning_rate': 1.04e-05, 'completion_length': 81.734375, 'rewards/reward_function': -275.796875, 'reward': -275.796875, 'reward_std': 83.43343734741211, 'kl': 0.0015386921004392207, 'epoch': 0.48}
{'loss': 0.0001, 'grad_norm': 0.3057001829147339, 'learning_rate': 9.600000000000001e-06, 'completion_length': 81.828125, 'rewards/reward_function': -274.765625, 'reward': -274.765625, 'reward_std': 87.30409622192383, 'kl': 0.0018212511204183102, 'epoch': 0.52}
{'loss': 0.0001, 'grad_norm': 0.29549792408943176, 'learning_rate': 8.8e-06, 'completion_length': 84.703125, 'rewards/reward_function': -294.34375, 'reward': -294.34375, 'reward_std': 78.55083465576172, 'kl': 0.0016118714702315629, 'epoch': 0.56}
{'loss': 0.0001, 'grad_norm': 0.3072602152824402, 'learning_rate': 8.000000000000001e-06, 'completion_length': 87.984375, 'rewards/reward_function': -287.5, 'reward': -287.5, 'reward_std': 61.97011184692383, 'kl': 0.0016941858921200037, 'epoch': 0.6}
{'loss': 0.0001, 'grad_norm': 0.2700439393520355, 'learning_rate': 7.2000000000000005e-06, 'completion_length': 80.75, 'rewards/reward_function': -270.796875, 'reward': -270.796875, 'reward_std': 82.61736297607422, 'kl': 0.0017022897372953594, 'epoch': 0.64}
{'loss': 0.0001, 'grad_norm': 0.22582575678825378, 'learning_rate': 6.4000000000000006e-06, 'completion_length': 87.859375, 'rewards/reward_function': -285.9375, 'reward': -285.9375, 'reward_std': 64.95146942138672, 'kl': 0.001648403995204717, 'epoch': 0.68}
{'loss': 0.0001, 'grad_norm': 0.27861785888671875, 'learning_rate': 5.600000000000001e-06, 'completion_length': 88.265625, 'rewards/reward_function': -285.390625, 'reward': -285.390625, 'reward_std': 75.81085205078125, 'kl': 0.001747835602145642, 'epoch': 0.72}
{'loss': 0.0001, 'grad_norm': 0.28778350353240967, 'learning_rate': 4.800000000000001e-06, 'completion_length': 86.828125, 'rewards/reward_function': -279.828125, 'reward': -279.828125, 'reward_std': 78.90678024291992, 'kl': 0.001816940726712346, 'epoch': 0.76}
{'loss': 0.0001, 'grad_norm': 0.3454166650772095, 'learning_rate': 4.000000000000001e-06, 'completion_length': 82.46875, 'rewards/reward_function': -279.03125, 'reward': -279.03125, 'reward_std': 79.5405158996582, 'kl': 0.002230603713542223, 'epoch': 0.8}
{'loss': 0.0001, 'grad_norm': 0.32247379422187805, 'learning_rate': 3.2000000000000003e-06, 'completion_length': 86.890625, 'rewards/reward_function': -281.625, 'reward': -281.625, 'reward_std': 66.91339874267578, 'kl': 0.0021375148789957166, 'epoch': 0.84}
{'loss': 0.0001, 'grad_norm': 0.313641756772995, 'learning_rate': 2.4000000000000003e-06, 'completion_length': 88.625, 'rewards/reward_function': -286.171875, 'reward': -286.171875, 'reward_std': 73.08686065673828, 'kl': 0.0016762455343268812, 'epoch': 0.88}
{'loss': 0.0001, 'grad_norm': 0.3753875195980072, 'learning_rate': 1.6000000000000001e-06, 'completion_length': 83.453125, 'rewards/reward_function': -270.421875, 'reward': -270.421875, 'reward_std': 91.96240234375, 'kl': 0.0016519528580829501, 'epoch': 0.92}
{'loss': 0.0001, 'grad_norm': 0.2510952949523926, 'learning_rate': 8.000000000000001e-07, 'completion_length': 88.40625, 'rewards/reward_function': -289.171875, 'reward': -289.171875, 'reward_std': 68.8226146697998, 'kl': 0.0016652905032970011, 'epoch': 0.96}
{'loss': 0.0001, 'grad_norm': 0.263446569442749, 'learning_rate': 0.0, 'completion_length': 88.515625, 'rewards/reward_function': -286.140625, 'reward': -286.140625, 'reward_std': 67.88261032104492, 'kl': 0.0017838834901340306, 'epoch': 1.0}
{'train_runtime': 427.907, 'train_samples_per_second': 0.467, 'train_steps_per_second': 0.058, 'train_loss': 6.59083854407072e-05, 'epoch': 1.0}
model.safetensors: 100%|██████████| 269M/269M [00:15<00:00, 17.0MB/s] 
Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1486, in _raise_on_head_call_error
    raise head_call_error
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 280, in _request_wrapper
    response = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 304, in _request_wrapper
    hf_raise_for_status(response)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 458, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-67dc32aa-42b6abc3207456c2327a0e23;923b7bfe-23e0-442f-b5ca-80149ecc5ed2)

Repository Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/dssc/scandu00/rebus-grpo/tutorial.py", line 97, in <module>
    generator = pipeline("text-generation", model="SmolGRPO-135M")
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/pipelines/__init__.py", line 812, in pipeline
    resolved_config_file = cached_file(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: SmolGRPO-135M is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1486, in _raise_on_head_call_error
    raise head_call_error
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 280, in _request_wrapper
    response = _request_wrapper(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 304, in _request_wrapper
    hf_raise_for_status(response)
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_http.py", line 458, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-67dc32aa-42b6abc3207456c2327a0e23;923b7bfe-23e0-442f-b5ca-80149ecc5ed2)

Repository Not Found for url: https://huggingface.co/SmolGRPO-135M/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/dssc/scandu00/rebus-grpo/tutorial.py", line 97, in <module>
    generator = pipeline("text-generation", model="SmolGRPO-135M")
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/pipelines/__init__.py", line 812, in pipeline
    resolved_config_file = cached_file(
  File "/orfeo/cephfs/home/dssc/scandu00/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: SmolGRPO-135M is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
